steps:
  - name: 'gcr.io/cloud-builders/docker'
    env:
      - 'DOCKER_BUILDKIT=0'
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/kairoagent-497417/kairo/kairo-app:cloudrun
      - .
  - name: 'gcr.io/cloud-builders/docker'
    env:
      - 'DOCKER_BUILDKIT=0'
    args:
      - push
      - us-central1-docker.pkg.dev/kairoagent-497417/kairo/kairo-app:cloudrun
