steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - --platform
      - linux/amd64
      - -t
      - us-central1-docker.pkg.dev/kairoagent-497417/kairo/kairo-app:latest
      - .

images:
  - us-central1-docker.pkg.dev/kairoagent-497417/kairo/kairo-app:latest
