ES_URL = "https://my-elasticsearch-project-d9aecb.es.europe-west1.gcp.elastic.cloud:443"
ES_USERNAME = "elastic"
ES_PASSWORD = "dNZBYMpC*u$!r7A"
ES_API_KEY_ID = "aDJYbFg1NEJVNTE3RGRHZXZjUjk6WHk4QmkxcHl3VTN2WVZHd2QyaHlkQQ=="
GEMINI_KEY = "AIzaSyDf8uUKnKuGmrlYQeZRXQhxKw2uZxVvCpY"
GEMINI_MODEL = "gemini-2.5-flash"
LOG_LEVEL = "INFO"
DEBUG = false
DEMO_MODE = false
